# Peak
[peak]
reference_values.maximum = -3  # dB
reference_values.minimum = -80  # dB

# True Peak
[true_peak]
reference_values.maximum = -1  # dB
reference_values.minimum = -80  # dB

# Peak-to-Average Power ratio in dB, also known as Crest Factor
[papr]
reference_values.maximum = -1  # dB
reference_values.minimum = -80  # dB

# RMS
[rms]
settings.window = 300  # Milliseconds, defaults to 300
reference_values.maximum = -1  # dB
reference_values.minimum = -12  # dB
